"""Hourly editorial brief: dark-styled HTML rundown, saved to the briefings
table (and disk) and emailed via Gmail SMTP when EMAIL_ENABLED."""

import logging
import smtplib
import ssl
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from jinja2 import Template

from app import config, db
from app.news.ingest import get_rundown

log = logging.getLogger("newsroom.briefing")

BRIEF_TEMPLATE = Template("""\
<!DOCTYPE html>
<html><body style="margin:0;padding:24px;background:#0F1419;font-family:Arial,Helvetica,sans-serif;color:#E7E9EA;">
<table width="100%" cellpadding="0" cellspacing="0" style="max-width:720px;margin:0 auto;">
<tr><td>
  <h1 style="font-size:20px;margin:0 0 4px;color:#fff;">NEWSROOM INTELLIGENCE BRIEF</h1>
  <p style="margin:0 0 20px;color:#8B98A5;font-size:13px;">Definitive rundown — {{ generated_at }} IST · advisory only, editor approval required</p>
  {% for s in stories %}
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#16202A;border-radius:8px;margin-bottom:12px;border-left:4px solid {{ '#E02424' if s.status == 'breaking' else '#059669' if s.status == 'verified' else '#D97706' }};">
  <tr><td style="padding:14px 16px;">
    <div style="font-size:12px;color:#8B98A5;margin-bottom:4px;">
      #{{ loop.index }} · <b style="color:{{ '#E02424' if s.status == 'breaking' else '#059669' if s.status == 'verified' else '#D97706' }};">{{ s.status | upper }}</b>
      · {{ s.category }} · {{ s.location }}
      {% if s.high_demand %} · <b style="color:#E02424;">HIGH-DEMAND AIRTIME RECOMMENDATION</b>{% endif %}
      {% if s.needs_review %} · <b style="color:#D97706;">NEEDS HUMAN REVIEW</b>{% endif %}
    </div>
    <div style="font-size:15px;font-weight:bold;color:#fff;margin-bottom:6px;">{{ s.title }}</div>
    <div style="font-size:12px;color:#8B98A5;margin-bottom:8px;">{{ s.publisher }}{% if s.sources|length > 1 %} + {{ s.sources|length - 1 }} corroborating source(s){% endif %} · confidence {{ s.confidence }}%</div>
    <div style="font-size:22px;font-weight:bold;color:#1D9BF0;">{{ s.score }}<span style="font-size:12px;color:#8B98A5;">/100</span></div>
    <div style="font-size:12px;color:#8B98A5;margin-top:6px;">
      {% for b in s.breakdown if b.points > 0 %}{{ b.variable }} +{{ b.points }}{{ ", " if not loop.last }}{% endfor %}
      {% if s.trend_boost > 0 %}<br><b style="color:#1D9BF0;">🚀 X trend boost +{{ s.trend_boost }}</b>{% endif %}
      {% if s.decay > 0 %}<br>repetitive decay −{{ s.decay }}{% endif %}
    </div>
    {% set evs = [] %}{% for b in s.breakdown %}{% for e in b.evidence %}{% if evs.append(e) %}{% endif %}{% endfor %}{% endfor %}
    {% if evs %}<div style="font-size:11px;color:#5C6B7A;margin-top:8px;">Evidence: {{ evs[:4] | join(' · ') }}</div>{% endif %}
  </td></tr></table>
  {% else %}
  <p style="color:#8B98A5;">No active stories this cycle.</p>
  {% endfor %}
  <p style="font-size:11px;color:#5C6B7A;margin-top:20px;">Generated by the AI Newsroom Dashboard. Rankings are evidence-based advisories; final rundown control remains with human executive editors.</p>
</td></tr></table>
</body></html>
""")


def build_brief() -> tuple[str, str]:
    stories = get_rundown(limit=10)
    now = datetime.now()
    subject = f"Newsroom Brief — {now:%d %b %Y, %H:00} — Top: {stories[0]['title'][:60] if stories else 'no stories'}"
    html = BRIEF_TEMPLATE.render(
        stories=stories, generated_at=f"{now:%d %b %Y %H:%M}"
    )
    return subject, html


def send_email(subject: str, html: str) -> str | None:
    """Returns an error string, or None on success."""
    if not config.EMAIL_ENABLED:
        return "email disabled (EMAIL_ENABLED=false)"
    if not config.GMAIL_ADDRESS or not config.GMAIL_APP_PASSWORD:
        return "missing GMAIL_ADDRESS / GMAIL_APP_PASSWORD"
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.GMAIL_ADDRESS
    msg["To"] = config.BRIEF_RECIPIENT
    msg.attach(MIMEText(html, "html"))
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465,
                              context=ssl.create_default_context()) as server:
            server.login(config.GMAIL_ADDRESS, config.GMAIL_APP_PASSWORD)
            server.sendmail(config.GMAIL_ADDRESS, [config.BRIEF_RECIPIENT],
                            msg.as_string())
        return None
    except Exception as exc:
        log.error("brief email failed: %s", exc)
        return str(exc)


def generate_and_send() -> dict:
    subject, html = build_brief()
    error = send_email(subject, html)
    now_iso = datetime.now(timezone.utc).isoformat()
    with db.connect() as con:
        con.execute(
            "INSERT INTO briefings (created_at, subject, html, emailed, email_error) "
            "VALUES (?,?,?,?,?)",
            (now_iso, subject, html, int(error is None), error),
        )
    config.BRIEF_OUT_DIR.mkdir(exist_ok=True)
    out = config.BRIEF_OUT_DIR / f"brief_{datetime.now():%Y%m%d_%H%M}.html"
    out.write_text(html, encoding="utf-8")
    return {"subject": subject, "emailed": error is None, "error": error,
            "saved_to": str(out)}
